language: ruby
rvm:
  - 2.1.0
  - 2.0.0
  - rbx-2.2.5
  - jruby-19mode
  - ruby-head
  - jruby-head
jdk:
  - oraclejdk7
  - openjdk7
matrix:
  exclude:
    - rvm: 2.1.0
      jdk: openjdk7
    - rvm: 2.0.0
      jdk: openjdk7
    - rvm: rbx-2.2.5
      jdk: openjdk7
    - rvm: ruby-head
      jdk: openjdk7
